export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const FETCH_PLANETS = "FETCH_PLANETS";
export const INCREMENT_VEHICLE_COUNT = "INCREMENT_VEHICLE_COUNT";
export const DECREMENT_VEHICLE_COUNT = "DECREMENT_VEHICLE_COUNT";
export const UPDATE_SEARCH_TIME = "UPDATE_SEARCH_TIME";
export const GET_API_TOKEN = "GET_API_TOKEN";
export const GET_ERRORS = "GET_ERRORS";
export const FIND_FALCONE = "FIND_FALCONE";
